<table>
    <thead>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>abc</td>
            <td>1000</td>
        </tr>
        <tr>
            <td>1</td>
            <td>abc</td>
            <td>1000</td>
        </tr>
        <tr>
            <td>1</td>
            <td>abc</td>
            <td>1000</td>
        </tr>
        <tr>
            <td>1</td>
            <td>abc</td>
            <td>1000</td>
        </tr>
    </tbody>
</table>